query getMenu {
	primaryMenu: menuItems(where: { location: PRIMARY }, first: 100) {
		nodes {
			id
			label
			url
			uri # Add this for relative paths
			parentId
			order # Add this for proper ordering
			childItems(first: 100) {
				nodes {
					id
					label
					url
					uri
					order
				}
			}
		}
	}

	footerMenu: menuItems(where: { location: FOOTER }, first: 100) {
		nodes {
			id
			label
			url
			uri
			parentId
			order
			childItems(first: 100) {
				nodes {
					id
					label
					url
					uri
					order
				}
			}
		}
	}
}
